### ISSUE TITLE
Create an Http service extension

### ISSUE THREAD

**Issue by sinedied** [angular-starter-kit/ngx-starter-kit#14]
Provide support for server configuration depending of the environment, default headers and user-configurable cache policy.

Should go in `core` module.

**Comment by moshmage** [comment]
How would I go about extending this?
I tried to provide a `AuthService` (which holds a `Authorization: Bearer <token>`), and then (on `private httpRequest`) made an `extend({}, options, { headers: new Headers('Authorization', this.authService.token) })`

but the constructor never get the `authService` (comming with `undefined` as its value on a console.log)

What I did:
- core.module.ts add `authService` to the `providers`
- add `authService` to the `createHttpService` return function
- add `authService` to `http.service.ts` constructor
- console.log(authService) 
- ???
- don't profit because it comes out undefined :(

What I'm trying to do:
Hook `"Authorization: Bearer <token>"` to every http request call

**Comment by sinedied** [comment]
Seems like an injection issue, is your `core.module.ts` `createHttpService` like this
```ts
export function createHttpService(backend: ConnectionBackend,
                                  defaultOptions: RequestOptions,
                                  httpCacheService: HttpCacheService,
                                  authService: AuthService) {
  return new HttpService(backend, defaultOptions, httpCacheService, authService);
}
```
and your `HttpService` constructor like this?
```ts
  constructor(backend: ConnectionBackend,
              private defaultOptions: RequestOptions,
              private httpCacheService: HttpCacheService,
              private authService: AuthService) {
    super(backend, defaultOptions);
  }
```

If it works for `httpCacheService`, it should work for your `authService`.

As for catching 401 error, you can just hook to the `httpRequest` or `errorHandler` methods.

**Comment by moshmage** [comment]
Yep, That's exactly how I set up - and what I thought ("if it works for httpCache it should work for auth")

I ended up making a layer between the Http and the app, httpClient, which will then call the Http. It's ugly, but I ain't have that much time;

Will revisit this approach later and submit a propper issue if stuff goes haywire :)

**Comment by sinedied** [comment]
~ ps: My approach would also induce in a circular dependency

Ah, that's the issue here! Since there's no way to properly resolve such dependencies, one of the required service ends up `undefined`. I'm surprised Angular did not throw some error or warning in the console though.

You should properly separate the 3 concerns here: getting authentified, storing/getting credentials and providing an customized http service. That should be 3 different services, and the service for storing/getting the credentials will act as the middleman here to avoid having a circular dependency.

Good luck ;)
